apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudtask-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/venkatnikhil616/CloudForge.git'
    targetRevision: HEAD
    path: deployments/helm/cloudtask
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudtask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
