apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cloudtask
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      serviceAccountName: cloudtask-service-account
      containers:
        - name: notification-service
          image: cloudtask/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9093
              name: metrics
          envFrom:
            - configMapRef:
                name: cloudtask-config
            - secretRef:
                name: cloudtask-secrets
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
